[tool.poetry]
name = "local-function-calling"
version = "0.1.0"
description = ""
authors = ["Jose Berrio <aldarisbm@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
jinja2 = "^3.1.2"
langchain = "^0.0.327"
llama-index = "^0.8.56"
llama-cpp-python = "^0.2.11"
python-dotenv = "^1.0.0"
uszipcode = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

